# Generated by Django 6.0.5 on 2026-06-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_electricityreading_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantasset',
            name='counts_down',
            field=models.BooleanField(default=False, help_text='If True, the reading decreases over time (e.g. 3000→2999). Delta is treated as absolute consumption.'),
        ),
    ]
