# Generated by Django 6.0.5 on 2026-05-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_employeeprofile_probation_status'),
        ('tenants', '0002_seed_aec_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_work_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incentives', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement_requests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_tasks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day'), ('CASUAL', 'Casual Leave'), ('EMERGENCY', 'Emergency')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'code'), ('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('tenant', 'name', 'date')},
        ),
    ]
