# Generated by Django 6.0.5

from django.db import migrations

MODELS_TO_BACKFILL = [
    ('core', 'User'),
    ('core', 'Department'),
    ('core', 'EmployeeProfile'),
    ('core', 'Attendance'),
    ('core', 'LeaveRequest'),
    ('core', 'Incentive'),
    ('core', 'Payroll'),
    ('core', 'AuditLog'),
    ('core', 'Holiday'),
    ('core', 'DailyWorkLog'),
    ('core', 'ReimbursementRequest'),
    ('core', 'StaffTask'),
]


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    try:
        tenant = Tenant.objects.get(id=1)
    except Tenant.DoesNotExist:
        # Fallback if id=1 is not yet present, though seeded in tenants.0002
        tenant = Tenant.objects.first()
        if not tenant:
            tenant = Tenant.objects.create(
                id=1,
                name='AEC Cinemas',
                slug='aec-cinemas',
                is_active=True,
                plan='pro',
                timezone='Asia/Kolkata',
                currency='INR',
                working_days_per_month=26,
            )

    for app_label, model_name in MODELS_TO_BACKFILL:
        try:
            Model = apps.get_model(app_label, model_name)
            updated = Model.objects.filter(tenant__isnull=True).update(tenant=tenant)
            if updated > 0:
                print(f"\n  ✓ {app_label}.{model_name}: {updated} rows → AEC tenant")
        except LookupError:
            # Model might not be loaded or exist
            pass


def reverse_backfill(apps, schema_editor):
    for app_label, model_name in MODELS_TO_BACKFILL:
        try:
            Model = apps.get_model(app_label, model_name)
            Model.objects.update(tenant=None)
        except LookupError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_holiday_unique_together_attendance_tenant_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_tenant, reverse_backfill),
    ]
