# Generated by Django 6.0.5 on 2026-06-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_districtdcrreport_posting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdcrreport',
            name='parsed_kfc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='parsed_repbeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
