# Generated by Django 5.1.5

from django.db import migrations

AEC_MODULES = [
    'OPERATIONS',
    'LAMP_REGISTRY',
    'SCREEN_BUILDER',
    'PRICING_ENGINE',
    'CAFE',
    'ADVERTISING',
    'FINANCE',
    'MD_DASHBOARD',
    'AUDIT',
    'BOOKINGS',
    'PAYROLL_MIRROR',
    'DISTRICT_BRIDGE',
]


def insert_aec_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    TenantModule = apps.get_model('tenants', 'TenantModule')

    tenant, created = Tenant.objects.get_or_create(
        id=1,
        defaults={
            'name': 'AEC Cinemas',
            'slug': 'aec-cinemas',
            'is_active': True,
            'plan': 'pro',
            'timezone': 'Asia/Kolkata',
            'currency': 'INR',
            'working_days_per_month': 26,
        }
    )

    for module_key in AEC_MODULES:
        TenantModule.objects.get_or_create(
            tenant=tenant,
            module_key=module_key,
            defaults={'is_enabled': True}
        )

    print(f"\n  ✓ AEC Cinemas created as Tenant Zero (id={tenant.id})")
    print(f"  ✓ {len(AEC_MODULES)} modules enabled for AEC tenant")


def remove_aec_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    Tenant.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_aec_tenant, remove_aec_tenant),
    ]
